# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test8LoginTestAdmin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_8LoginTestAdmin(self):
    self.driver.get("http://18.222.217.197/")
    self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.ID, "username-field").click()
    self.vars["Admin_08"] = self.driver.execute_script("document.querySelector(\'#username-field\').value=\'Admin_08\'")
    self.driver.find_element(By.CSS_SELECTOR, ".button-row").click()
    self.driver.find_element(By.ID, "password-field").click()
    self.driver.find_element(By.CSS_SELECTOR, ".panel").click()
    self.driver.find_element(By.ID, "password-field").click()
    self.vars["Pass_eight"] = self.driver.execute_script("document.querySelector(\'#password-field\').value=\'Pass_eight\'")
    self.driver.find_element(By.NAME, "action").click()
    time.sleep(10)
  
