# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test15LogoutButtonTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_15LogoutButtonTest(self):
    self.driver.get("http://18.222.217.197/")
    self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.ID, "username-field").click()
    self.vars["Admin_08"] = self.driver.execute_script("document.querySelector(\'#username-field\').value=\'Admin_08\'")
    self.driver.find_element(By.ID, "password-field").click()
    self.vars["Pass_eight"] = self.driver.execute_script("document.querySelector(\'#password-field\').value=\'Pass_eight\'")
    self.driver.find_element(By.NAME, "action").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "View Ticket").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Edit Ticket").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_description").click()
    self.vars["This is a test ticket. I am making an edit and I am changing this ticket to closed"] = self.driver.execute_script("document.querySelector(\'#id_description\').value=\'This is a test ticket. I am making an edit and I am changing this ticket to closed\'")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_status").click()
    dropdown = self.driver.find_element(By.ID, "id_status")
    dropdown.find_element(By.XPATH, "//option[. = 'Closed']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_status > option:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Account").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1)").click()
    time.sleep(2)
  
