# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test10SearchPageAdmin08():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_10SearchPageAdmin08(self):
    self.driver.get("http://18.222.217.197/")
    self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.ID, "username-field").click()
    self.vars["Admin_08"] = self.driver.execute_script("document.querySelector(\'#username-field\').value=\'Admin_08\'")
    self.driver.find_element(By.ID, "password-field").click()
    self.vars["Pass_eight"] = self.driver.execute_script("document.querySelector(\'#password-field\').value=\'Pass_eight\'")
    self.driver.find_element(By.NAME, "action").click()
    time.sleep(2)
    self.driver.get("http://18.222.217.197/search/")
    self.driver.find_element(By.LINK_TEXT, "Search").click()
    self.driver.find_element(By.ID, "q").click()
    self.vars["help"] = self.driver.execute_script("document.querySelector(\'#q\').value=\'help\'")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "View Ticket").click()
    time.sleep(5)
    self.driver.find_element(By.LINK_TEXT, "Search").click()
    self.driver.find_element(By.ID, "q").click()
    self.driver.find_element(By.ID, "status").click()
    dropdown = self.driver.find_element(By.ID, "status")
    dropdown.find_element(By.XPATH, "//option[. = 'Open']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.ID, "status").click()
    dropdown = self.driver.find_element(By.ID, "status")
    dropdown.find_element(By.XPATH, "//option[. = 'In Progress']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.ID, "status").click()
    dropdown = self.driver.find_element(By.ID, "status")
    dropdown.find_element(By.XPATH, "//option[. = 'Closed']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    time.sleep(5)
  
