# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test7LogoutButtonTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_7LogoutButtonTest(self):
    self.driver.get("http://18.222.217.197/")
    self.driver.find_element(By.ID, "username-field").click()
    self.vars["Testuser"] = self.driver.execute_script("document.querySelector(\'#username-field\').value=\'Testuser\'")
    self.driver.find_element(By.ID, "password-field").click()
    self.vars["testtesttest"] = self.driver.execute_script("document.querySelector(\'#password-field\').value=\'testtesttest\'")
    self.driver.find_element(By.NAME, "action").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(5)
    self.driver.close()
  
