# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test12AccountCreation():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_12AccountCreation(self):
    self.driver.get("http://18.222.217.197/")
    self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.ID, "username-field").click()
    self.vars["Admin_08"] = self.driver.execute_script("document.querySelector(\'#username-field\').value=\'Admin_08\'")
    self.driver.find_element(By.ID, "password-field").click()
    self.vars["Pass_eight"] = self.driver.execute_script("document.querySelector(\'#password-field\').value=\'Pass_eight\'")
    self.driver.find_element(By.NAME, "action").click()
    time.sleep(2)
    self.driver.get("http://18.222.217.197/account/")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.LINK_TEXT, "Create Account").click()
    self.vars["Testuser2"] = self.driver.execute_script("document.querySelector(\'#id_username\').value=\'Testuser2\'")
    self.driver.find_element(By.ID, "id_password").click()
    self.vars["Password"] = self.driver.execute_script("document.querySelector(\'#id_password\').value=\'Password\'")
    self.driver.find_element(By.ID, "id_role").click()
    dropdown = self.driver.find_element(By.ID, "id_role")
    dropdown.find_element(By.XPATH, "//option[. = 'User']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    time.sleep(5)
    self.driver.find_element(By.LINK_TEXT, "Cancel").click()
    time.sleep(5)
  
