# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test4AccountButtonandUpdateTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_4AccountButtonandUpdateTest(self):
    self.driver.get("http://18.222.217.197/")
    self.driver.set_window_size(1095, 840)
    self.driver.find_element(By.LINK_TEXT, "Account").click()
    self.driver.find_element(By.ID, "id_first_name").click()
    self.vars["John"] = self.driver.execute_script("document.querySelector(\'#id_first_name\').value=\'John\'")
    self.driver.find_element(By.ID, "id_last_name").click()
    self.vars["Doe"] = self.driver.execute_script("document.querySelector(\'#id_last_name\').value=\'Doe\'")
    self.driver.find_element(By.ID, "id_email").click()
    self.vars["someemail@gmail.com"] = self.driver.execute_script("document.querySelector(\'#id_email\').value=\'someemail@gmail.com\'")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(6)").click()
    time.sleep(5)
  
